### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Izocel**

### CODE REVIEW

**Comment by Izocel** [comment]
Task linked: [CU-866b647bx Test-WTC-0000](https://app.clickup.com/t/866b647bx)

**Review by CtrlAiDel — APPROVED** [review]

**Review by CtrlAiDel — APPROVED** [review]

**Comment by Izocel** [comment]
CU-866b647bx/Test-WTC-0000[merged]

**Comment by Izocel** [comment]
CU-866b647bx[merged]

**Comment by Izocel** [comment]
CU-866b647bx[MERGED]

**Pull request merged**
